### ISSUE TITLE
Failed to crop - wrong number of arguments (1 for 3, 4, or 5)

### ISSUE THREAD

**Issue by vjandrei** [evg2108/carrierwave-crop-on-fly#1]
Hi, nice fork from the orginal one.
I have this issue   
# POST /users.json

  def create
    @user = User.new(user_params)

```
respond_to do |format|
  if @user.save
```

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"MRa4sEXNc5+sfOkPMuy49YhR76Ykkixb5FPO9HK/s+k8uxAibLPWHHA940Zp0sXhZ+WAP1uew5tSNQIknk2MAQ==",
 "user"=>{"avatar"=>#<ActionDispatch::Http::UploadedFile:0x007fa93a231be0 @crop_x="135.46",
 @crop_y="100.72666666666666",
 @crop_w="538.3666666666667",
 @crop_h="618.2533333333333",
 @tempfile=#<Tempfile:/var/folders/_0/q8fjlt_537x1qf7f8jx500dc0000gn/T/RackMultipart20151217-63314-9yhro2.jpg>,
 @original_filename="andreas-2.jpg",
 @content_type="image/jpeg",
 @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"andreas-2.jpg\"\r\nContent-Type: image/jpeg\r\n">,
 "avatar_cache"=>""},
 "commit"=>"Crop"}

My private controller for user looks like this 
 private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

```
# Never trust parameters from the scary internet, only allow the white list through.
def user_params
  params.require(:user).permit(:avatar, {avatars: []}, :avatar_cache, :favatar_crop_x, :avatar_crop_y, :avatar_crop_w, :avatar_crop_h)
end
```

end

**Comment by evg2108** [comment]
Hello.

May i see what in AvatarUploader and how they mounted to User model?

And what Rails version you use?

**Comment by vjandrei** [comment]
Hi, sure here is the demo repo I have try 
https://github.com/vjandrei/rails4_carrierwave-crop-on-fly_demo

**Comment by evg2108** [comment]
In AvatarUploader you need set output sizes, like this:

``` Ruby
process crop: [100, 100]
```

instead of

``` Ruby
process crop: :avatar
```

**Comment by vjandrei** [comment]
I change it and now I get Failed to crop - undefined method `to_f' for :avatar:Symbol

 def create
     @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html {

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"9aUTr0zJ+WtK7wssYVnI36tyIHGtStaMpawJ0ZxyT7z4CLs9Zbdc6JauAWU6Z7XLRMZP6NJGOUwTysUBcIBwVA==",
 "user"=>{"avatar"=>#<ActionDispatch::Http::UploadedFile:0x007fe26f40ef58 @crop_x="90.30666666666667",
 @crop_y="159.7733333333333",
 @crop_w="531.4200000000001",
 @crop_h="531.42",
 @tempfile=#<Tempfile:/var/folders/_0/q8fjlt_537x1qf7f8jx500dc0000gn/T/RackMultipart20151217-65724-6hl0p7.jpg>,
 @original_filename="andreas-2.jpg",
 @content_type="image/jpeg",
 @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"andreas-2.jpg\"\r\nContent-Type: image/jpeg\r\n">,
 "avatar_cache"=>""},
 "commit"=>"Crop"}

**Comment by evg2108** [comment]
show me stacktrace please

**Comment by vjandrei** [comment]
Here is app/controllers/users_controller.rb:28:in `create'

**Comment by evg2108** [comment]
You have 2 places where you are use `crop`

in file app/uploaders/avatar_uploader.rb in line #12 replace

``` Ruby
 process crop: :avatar
```

to

``` Ruby
 process crop: [800, 600]
```

and in line #49 replace

``` Ruby
  version :thumb do
    process crop: :avatar  ## Crops this version based on original image
    resize_to_limit(100,100)
  end
```

to

``` Ruby
  version :thumb do
    process crop: [100,100]  ## Crops this version based on original image
    #resize_to_limit(100,100)
  end
```

For correct work, you should use array of sizes

I check this on my computer, and this work

**Comment by vjandrei** [comment]
Great now it works! How about one think. Do I need the crop.html.erb file?
Now after the file upload first crop submit it will redirect to to crop.html.erb ?

**Comment by vjandrei** [comment]
I just figured out that one my self :) thanks for the help!

**Comment by evg2108** [comment]
You are welcome
