### ISSUE TITLE
Problem with reupload image

### ISSUE THREAD

**Issue by QNester** [evg2108/carrierwave-crop-on-fly#3]
Hi. Thanks for your gem! I have one problem with reupload image.
I select image with aspect 16:9 from my pc, cropbox works correct. After i would exchange this image(16:9) with image 4:5 and this look so stretched. Can you help me solve my problem?

PS Sorry for my bad English :(

**Comment by evg2108** [comment]
I'll see what I can do on this weekend

**Comment by evg2108** [comment]
I try to do this, and cropbox works correct after change image with another aspect.
May you show me your code?

PS Sorry for my bad English too :)
PPS Do you speak Russian?

**Comment by QNester** [comment]
Говорю по-русски, уже разобрался) Видимо нужно ночью чаще спать :smile: Спасибо за гем! Очень помог!

**Comment by evg2108** [comment]
Да не за что. Пользуйся на здоровье :)
